//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BookHub.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Payment
    {
        public int PaymentID { get; set; }
        public int UserID { get; set; }
        public int OrderID { get; set; }
        public System.DateTime PaymentTime { get; set; }
        public string PaymentMethod { get; set; }
    
        public virtual Order Order { get; set; }
        public virtual User User { get; set; }
    }
}
